tenancy_ocid = ""
user_ocid = ""
fingerprint = ""
private_key_path = ""
region = "eu-frankfurt-1"
compartment_ocid = "ocid1.compartment.oc1..aaaaaaaahtgk3enkqzd74e7nmnidhsltucmrhm22ye6lffwmcdrpnq2xlloq"
